---
- name: create inventory
  hosts: jumpbox
  roles:
    - role: osp_facts

- name: deploy haproxy
  become: true
  hosts: frontends
  roles:
    - role: configuration
    - role: deploy-haproxy

- name: deploy tomcat
  become: true
  hosts: apps
  roles:
    - role: configuration
    - role: deploy-tomcat

- name: deploy postgres
  become: true
  hosts: appdbs
  roles:
    - role: configuration
    - { role: geerlingguy.postgresql }

- name: deploy apache
  become: true
  hosts: apps
  roles:
  - role: deploy-apache
